### ISSUE TITLE
Any reason why updated version of this library can't stay .netstandard20 or 21?

### ISSUE THREAD

**Issue by gaborbuzasi** [IdentityServer/IdentityServer4.AccessTokenValidation#136]
### Question
Previous versions of this library were released as .netstandard20 and with the new release it is not impossible to use this library in a common project that is targeting .netstandard20 or 21.

Would it be possible to change this back so that this library can be included in projects targeting .netstandard?

**Comment by leastprivilege** [comment]
No. Because ASP.NET Core itself targets netcore31

**Comment by Tri125** [comment]
But .NET Core 3.1 implement .NET Standard 2.1. [See](https://dotnet.microsoft.com/platform/dotnet-standard#versions).

I'm currently upgrading a ASP.NET Core software from 2.1 to 3.1.

The solution have multiple projects. The main asp net project is now targeting ``netcoreapp3.1``.

The asp net project have a reference to multiple library class that now targets ``netstandard2.1``.

Some of those projects are responsible to configure part of the asp net app.

Because IdentityServer4 don't target ``netstandard2.1`` we can't use the package in a library class project.

**Comment by leastprivilege** [comment]
I think the OP question has been answered. That's the way it works,
